---
title: "Sowmya_EDA - Before balancing the dataset"
author: "Sowmya"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# importing the ezids package
library(ezids)

# importing ggplot2 for graphs
library(ggplot2)
library(gridExtra)
```

# Brain Stroke Prediction

```{r}
loadPkg("corrplot")
stroke_df = read.csv("healthcare-dataset-stroke-data.csv")
stroke_df = subset(stroke_df, select = -c(id))
head(stroke_df)

# Getting the summary of the dataframe
summary(stroke_df)


# Looking at the structure of the Dataframe
str(stroke_df)
```

```{r}
# changing the variables to categorical variables and numerical variables
stroke_df$gender <- as.factor(stroke_df$gender)
stroke_df$hypertension <- as.factor(stroke_df$hypertension)
stroke_df$heart_disease <- as.factor(stroke_df$heart_disease)
stroke_df$ever_married <- as.factor(stroke_df$ever_married)
stroke_df$bmi <- as.numeric(stroke_df$bmi)
stroke_df$stroke<- as.factor(stroke_df$stroke)
str(stroke_df)

# Finding if there are any NA's in the dataset
paste("The NA's in the dataset is:",sum(is.na(stroke_df)))
summary(stroke_df)
```

```{r}
ggplot(stroke_df, aes(x = stroke, y = hypertension)) + ggtitle("Scatter plot for Hypertension vs Stroke")+ geom_point()
```

```{r, include=TRUE}
ht_plot <- ggplot(data = stroke_df, aes(hypertension, fill=hypertension))+geom_bar()+ ggtitle("Distribution of hypertension")
ht_plot

hd_plot <- ggplot(data = stroke_df, aes(heart_disease, fill=heart_disease))+geom_bar()+ggtitle("Distribution of heart disease")
hd_plot
```












